name: Build and Push Docker Images

on:
  push:
    branches:
      - main  # or the name of your default branch

jobs:
        build:
          runs-on: ubuntu-latest
          steps:
          # Previous steps omitted for brevity
      
          - name: Checkout code 
            uses: actions/checkout@v4

          - name: Set up QEMU
            uses: docker/setup-qemu-action@v3
      
          - name: Set up Docker buildx
            uses: docker/setup-buildx-action@v3
      
          - name: Login to DockerHub
            uses: docker/login-action@v3
            with:
              username: ${{ secrets.DOCKERHUB_USERNAME }}
              password: ${{ secrets.DOCKERHUB_TOKEN }}
      
          - name: Build and push multi-arch API Docker image with caching
            uses: docker/build-push-action@v5
            with:
              context: ./
              push: true
              tags: anasch07/ecommerce-backend-nestjs:latest
              platforms: linux/amd64,linux/arm64
              cache-from: type=gha
              cache-to: type=gha,mode=max
      


  
