name: Build and Push Docker Images

on:
  push:
    branches:
      - main  # or the name of your default branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code 
      uses: actions/checkout@v4

    - name: Login to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Set up Docker buildx
      uses: docker/setup-buildx-action@v3

    - name: Build and push API Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: anasch07/ecommerce-backend-express:latest

  
